// Code generated by SQLBoiler 4.10.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	AbnormalClaim      string
	Address            string
	ApplicationStatus  string
	Block              string
	Claim              string
	ClaimInList        string
	ClaimTag           string
	Input              string
	JobStatus          string
	Output             string
	Purchase           string
	Support            string
	Tag                string
	Transaction        string
	TransactionAddress string
}{
	AbnormalClaim:      "abnormal_claim",
	Address:            "address",
	ApplicationStatus:  "application_status",
	Block:              "block",
	Claim:              "claim",
	ClaimInList:        "claim_in_list",
	ClaimTag:           "claim_tag",
	Input:              "input",
	JobStatus:          "job_status",
	Output:             "output",
	Purchase:           "purchase",
	Support:            "support",
	Tag:                "tag",
	Transaction:        "transaction",
	TransactionAddress: "transaction_address",
}
