// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// Transaction is an object representing the database table.
type Transaction struct {
	ID              uint64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	BlockHashID     null.String `boil:"block_hash_id" json:"block_hash_id,omitempty" toml:"block_hash_id" yaml:"block_hash_id,omitempty"`
	InputCount      uint        `boil:"input_count" json:"input_count" toml:"input_count" yaml:"input_count"`
	OutputCount     uint        `boil:"output_count" json:"output_count" toml:"output_count" yaml:"output_count"`
	Fee             float64     `boil:"fee" json:"fee" toml:"fee" yaml:"fee"`
	TransactionTime null.Uint64 `boil:"transaction_time" json:"transaction_time,omitempty" toml:"transaction_time" yaml:"transaction_time,omitempty"`
	TransactionSize uint64      `boil:"transaction_size" json:"transaction_size" toml:"transaction_size" yaml:"transaction_size"`
	Hash            string      `boil:"hash" json:"hash" toml:"hash" yaml:"hash"`
	Version         int         `boil:"version" json:"version" toml:"version" yaml:"version"`
	LockTime        uint        `boil:"lock_time" json:"lock_time" toml:"lock_time" yaml:"lock_time"`
	Raw             null.String `boil:"raw" json:"raw,omitempty" toml:"raw" yaml:"raw,omitempty"`
	CreatedAt       time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	ModifiedAt      time.Time   `boil:"modified_at" json:"modified_at" toml:"modified_at" yaml:"modified_at"`
	CreatedTime     time.Time   `boil:"created_time" json:"created_time" toml:"created_time" yaml:"created_time"`

	R *transactionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L transactionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TransactionColumns = struct {
	ID              string
	BlockHashID     string
	InputCount      string
	OutputCount     string
	Fee             string
	TransactionTime string
	TransactionSize string
	Hash            string
	Version         string
	LockTime        string
	Raw             string
	CreatedAt       string
	ModifiedAt      string
	CreatedTime     string
}{
	ID:              "id",
	BlockHashID:     "block_hash_id",
	InputCount:      "input_count",
	OutputCount:     "output_count",
	Fee:             "fee",
	TransactionTime: "transaction_time",
	TransactionSize: "transaction_size",
	Hash:            "hash",
	Version:         "version",
	LockTime:        "lock_time",
	Raw:             "raw",
	CreatedAt:       "created_at",
	ModifiedAt:      "modified_at",
	CreatedTime:     "created_time",
}

// transactionR is where relationships are stored.
type transactionR struct {
	BlockHash               *Block
	TransactionHashClaims   ClaimSlice
	Inputs                  InputSlice
	Outputs                 OutputSlice
	TransactionHashSupports SupportSlice
	TransactionAddresses    TransactionAddressSlice
}

// transactionL is where Load methods for each relationship are stored.
type transactionL struct{}

var (
	transactionColumns               = []string{"id", "block_hash_id", "input_count", "output_count", "fee", "transaction_time", "transaction_size", "hash", "version", "lock_time", "raw", "created_at", "modified_at", "created_time"}
	transactionColumnsWithoutDefault = []string{"block_hash_id", "input_count", "output_count", "transaction_time", "transaction_size", "hash", "version", "lock_time", "raw"}
	transactionColumnsWithDefault    = []string{"id", "fee", "created_at", "modified_at", "created_time"}
	transactionPrimaryKeyColumns     = []string{"id"}
)

type (
	// TransactionSlice is an alias for a slice of pointers to Transaction.
	// This should generally be used opposed to []Transaction.
	TransactionSlice []*Transaction

	transactionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	transactionType                 = reflect.TypeOf(&Transaction{})
	transactionMapping              = queries.MakeStructMapping(transactionType)
	transactionPrimaryKeyMapping, _ = queries.BindMapping(transactionType, transactionMapping, transactionPrimaryKeyColumns)
	transactionInsertCacheMut       sync.RWMutex
	transactionInsertCache          = make(map[string]insertCache)
	transactionUpdateCacheMut       sync.RWMutex
	transactionUpdateCache          = make(map[string]updateCache)
	transactionUpsertCacheMut       sync.RWMutex
	transactionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)

// OneP returns a single transaction record from the query, and panics on error.
func (q transactionQuery) OneP() *Transaction {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single transaction record from the query.
func (q transactionQuery) One() (*Transaction, error) {
	o := &Transaction{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: failed to execute a one query for transaction")
	}

	return o, nil
}

// AllP returns all Transaction records from the query, and panics on error.
func (q transactionQuery) AllP() TransactionSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Transaction records from the query.
func (q transactionQuery) All() (TransactionSlice, error) {
	var o []*Transaction

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to Transaction slice")
	}

	return o, nil
}

// CountP returns the count of all Transaction records in the query, and panics on error.
func (q transactionQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Transaction records in the query.
func (q transactionQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count transaction rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q transactionQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q transactionQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if transaction exists")
	}

	return count > 0, nil
}

// BlockHashG pointed to by the foreign key.
func (o *Transaction) BlockHashG(mods ...qm.QueryMod) blockQuery {
	return o.BlockHash(boil.GetDB(), mods...)
}

// BlockHash pointed to by the foreign key.
func (o *Transaction) BlockHash(exec boil.Executor, mods ...qm.QueryMod) blockQuery {
	queryMods := []qm.QueryMod{
		qm.Where("hash=?", o.BlockHashID),
	}

	queryMods = append(queryMods, mods...)

	query := Blocks(exec, queryMods...)
	queries.SetFrom(query.Query, "`block`")

	return query
}

// TransactionHashClaimsG retrieves all the claim's claim via transaction_hash_id column.
func (o *Transaction) TransactionHashClaimsG(mods ...qm.QueryMod) claimQuery {
	return o.TransactionHashClaims(boil.GetDB(), mods...)
}

// TransactionHashClaims retrieves all the claim's claim with an executor via transaction_hash_id column.
func (o *Transaction) TransactionHashClaims(exec boil.Executor, mods ...qm.QueryMod) claimQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`claim`.`transaction_hash_id`=?", o.Hash),
	)

	query := Claims(exec, queryMods...)
	queries.SetFrom(query.Query, "`claim`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`claim`.*"})
	}

	return query
}

// InputsG retrieves all the input's input.
func (o *Transaction) InputsG(mods ...qm.QueryMod) inputQuery {
	return o.Inputs(boil.GetDB(), mods...)
}

// Inputs retrieves all the input's input with an executor.
func (o *Transaction) Inputs(exec boil.Executor, mods ...qm.QueryMod) inputQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`input`.`transaction_id`=?", o.ID),
	)

	query := Inputs(exec, queryMods...)
	queries.SetFrom(query.Query, "`input`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`input`.*"})
	}

	return query
}

// OutputsG retrieves all the output's output.
func (o *Transaction) OutputsG(mods ...qm.QueryMod) outputQuery {
	return o.Outputs(boil.GetDB(), mods...)
}

// Outputs retrieves all the output's output with an executor.
func (o *Transaction) Outputs(exec boil.Executor, mods ...qm.QueryMod) outputQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`output`.`transaction_id`=?", o.ID),
	)

	query := Outputs(exec, queryMods...)
	queries.SetFrom(query.Query, "`output`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`output`.*"})
	}

	return query
}

// TransactionHashSupportsG retrieves all the support's support via transaction_hash_id column.
func (o *Transaction) TransactionHashSupportsG(mods ...qm.QueryMod) supportQuery {
	return o.TransactionHashSupports(boil.GetDB(), mods...)
}

// TransactionHashSupports retrieves all the support's support with an executor via transaction_hash_id column.
func (o *Transaction) TransactionHashSupports(exec boil.Executor, mods ...qm.QueryMod) supportQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`support`.`transaction_hash_id`=?", o.Hash),
	)

	query := Supports(exec, queryMods...)
	queries.SetFrom(query.Query, "`support`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`support`.*"})
	}

	return query
}

// TransactionAddressesG retrieves all the transaction_address's transaction address.
func (o *Transaction) TransactionAddressesG(mods ...qm.QueryMod) transactionAddressQuery {
	return o.TransactionAddresses(boil.GetDB(), mods...)
}

// TransactionAddresses retrieves all the transaction_address's transaction address with an executor.
func (o *Transaction) TransactionAddresses(exec boil.Executor, mods ...qm.QueryMod) transactionAddressQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`transaction_address`.`transaction_id`=?", o.ID),
	)

	query := TransactionAddresses(exec, queryMods...)
	queries.SetFrom(query.Query, "`transaction_address`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`transaction_address`.*"})
	}

	return query
}

// LoadBlockHash allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (transactionL) LoadBlockHash(e boil.Executor, singular bool, maybeTransaction interface{}) error {
	var slice []*Transaction
	var object *Transaction

	count := 1
	if singular {
		object = maybeTransaction.(*Transaction)
	} else {
		slice = *maybeTransaction.(*[]*Transaction)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &transactionR{}
		}
		args[0] = object.BlockHashID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &transactionR{}
			}
			args[i] = obj.BlockHashID
		}
	}

	query := fmt.Sprintf(
		"select * from `block` where `hash` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Block")
	}
	defer results.Close()

	var resultSlice []*Block
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Block")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.BlockHash = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.BlockHashID.String == foreign.Hash {
				local.R.BlockHash = foreign
				break
			}
		}
	}

	return nil
}

// LoadTransactionHashClaims allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (transactionL) LoadTransactionHashClaims(e boil.Executor, singular bool, maybeTransaction interface{}) error {
	var slice []*Transaction
	var object *Transaction

	count := 1
	if singular {
		object = maybeTransaction.(*Transaction)
	} else {
		slice = *maybeTransaction.(*[]*Transaction)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &transactionR{}
		}
		args[0] = object.Hash
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &transactionR{}
			}
			args[i] = obj.Hash
		}
	}

	query := fmt.Sprintf(
		"select * from `claim` where `transaction_hash_id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load claim")
	}
	defer results.Close()

	var resultSlice []*Claim
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice claim")
	}

	if singular {
		object.R.TransactionHashClaims = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Hash == foreign.TransactionHashID.String {
				local.R.TransactionHashClaims = append(local.R.TransactionHashClaims, foreign)
				break
			}
		}
	}

	return nil
}

// LoadInputs allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (transactionL) LoadInputs(e boil.Executor, singular bool, maybeTransaction interface{}) error {
	var slice []*Transaction
	var object *Transaction

	count := 1
	if singular {
		object = maybeTransaction.(*Transaction)
	} else {
		slice = *maybeTransaction.(*[]*Transaction)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &transactionR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &transactionR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from `input` where `transaction_id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load input")
	}
	defer results.Close()

	var resultSlice []*Input
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice input")
	}

	if singular {
		object.R.Inputs = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.TransactionID {
				local.R.Inputs = append(local.R.Inputs, foreign)
				break
			}
		}
	}

	return nil
}

// LoadOutputs allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (transactionL) LoadOutputs(e boil.Executor, singular bool, maybeTransaction interface{}) error {
	var slice []*Transaction
	var object *Transaction

	count := 1
	if singular {
		object = maybeTransaction.(*Transaction)
	} else {
		slice = *maybeTransaction.(*[]*Transaction)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &transactionR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &transactionR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from `output` where `transaction_id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load output")
	}
	defer results.Close()

	var resultSlice []*Output
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice output")
	}

	if singular {
		object.R.Outputs = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.TransactionID {
				local.R.Outputs = append(local.R.Outputs, foreign)
				break
			}
		}
	}

	return nil
}

// LoadTransactionHashSupports allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (transactionL) LoadTransactionHashSupports(e boil.Executor, singular bool, maybeTransaction interface{}) error {
	var slice []*Transaction
	var object *Transaction

	count := 1
	if singular {
		object = maybeTransaction.(*Transaction)
	} else {
		slice = *maybeTransaction.(*[]*Transaction)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &transactionR{}
		}
		args[0] = object.Hash
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &transactionR{}
			}
			args[i] = obj.Hash
		}
	}

	query := fmt.Sprintf(
		"select * from `support` where `transaction_hash_id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load support")
	}
	defer results.Close()

	var resultSlice []*Support
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice support")
	}

	if singular {
		object.R.TransactionHashSupports = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Hash == foreign.TransactionHashID.String {
				local.R.TransactionHashSupports = append(local.R.TransactionHashSupports, foreign)
				break
			}
		}
	}

	return nil
}

// LoadTransactionAddresses allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (transactionL) LoadTransactionAddresses(e boil.Executor, singular bool, maybeTransaction interface{}) error {
	var slice []*Transaction
	var object *Transaction

	count := 1
	if singular {
		object = maybeTransaction.(*Transaction)
	} else {
		slice = *maybeTransaction.(*[]*Transaction)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &transactionR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &transactionR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from `transaction_address` where `transaction_id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load transaction_address")
	}
	defer results.Close()

	var resultSlice []*TransactionAddress
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice transaction_address")
	}

	if singular {
		object.R.TransactionAddresses = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.TransactionID {
				local.R.TransactionAddresses = append(local.R.TransactionAddresses, foreign)
				break
			}
		}
	}

	return nil
}

// SetBlockHashG of the transaction to the related item.
// Sets o.R.BlockHash to related.
// Adds o to related.R.BlockHashTransactions.
// Uses the global database handle.
func (o *Transaction) SetBlockHashG(insert bool, related *Block) error {
	return o.SetBlockHash(boil.GetDB(), insert, related)
}

// SetBlockHashP of the transaction to the related item.
// Sets o.R.BlockHash to related.
// Adds o to related.R.BlockHashTransactions.
// Panics on error.
func (o *Transaction) SetBlockHashP(exec boil.Executor, insert bool, related *Block) {
	if err := o.SetBlockHash(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetBlockHashGP of the transaction to the related item.
// Sets o.R.BlockHash to related.
// Adds o to related.R.BlockHashTransactions.
// Uses the global database handle and panics on error.
func (o *Transaction) SetBlockHashGP(insert bool, related *Block) {
	if err := o.SetBlockHash(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetBlockHash of the transaction to the related item.
// Sets o.R.BlockHash to related.
// Adds o to related.R.BlockHashTransactions.
func (o *Transaction) SetBlockHash(exec boil.Executor, insert bool, related *Block) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `transaction` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"block_hash_id"}),
		strmangle.WhereClause("`", "`", 0, transactionPrimaryKeyColumns),
	)
	values := []interface{}{related.Hash, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.BlockHashID.String = related.Hash
	o.BlockHashID.Valid = true

	if o.R == nil {
		o.R = &transactionR{
			BlockHash: related,
		}
	} else {
		o.R.BlockHash = related
	}

	if related.R == nil {
		related.R = &blockR{
			BlockHashTransactions: TransactionSlice{o},
		}
	} else {
		related.R.BlockHashTransactions = append(related.R.BlockHashTransactions, o)
	}

	return nil
}

// RemoveBlockHashG relationship.
// Sets o.R.BlockHash to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle.
func (o *Transaction) RemoveBlockHashG(related *Block) error {
	return o.RemoveBlockHash(boil.GetDB(), related)
}

// RemoveBlockHashP relationship.
// Sets o.R.BlockHash to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Panics on error.
func (o *Transaction) RemoveBlockHashP(exec boil.Executor, related *Block) {
	if err := o.RemoveBlockHash(exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveBlockHashGP relationship.
// Sets o.R.BlockHash to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle and panics on error.
func (o *Transaction) RemoveBlockHashGP(related *Block) {
	if err := o.RemoveBlockHash(boil.GetDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveBlockHash relationship.
// Sets o.R.BlockHash to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *Transaction) RemoveBlockHash(exec boil.Executor, related *Block) error {
	var err error

	o.BlockHashID.Valid = false
	if err = o.Update(exec, "block_hash_id"); err != nil {
		o.BlockHashID.Valid = true
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.BlockHash = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.BlockHashTransactions {
		if o.BlockHashID.String != ri.BlockHashID.String {
			continue
		}

		ln := len(related.R.BlockHashTransactions)
		if ln > 1 && i < ln-1 {
			related.R.BlockHashTransactions[i] = related.R.BlockHashTransactions[ln-1]
		}
		related.R.BlockHashTransactions = related.R.BlockHashTransactions[:ln-1]
		break
	}
	return nil
}

// AddTransactionHashClaimsG adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.TransactionHashClaims.
// Sets related.R.TransactionHash appropriately.
// Uses the global database handle.
func (o *Transaction) AddTransactionHashClaimsG(insert bool, related ...*Claim) error {
	return o.AddTransactionHashClaims(boil.GetDB(), insert, related...)
}

// AddTransactionHashClaimsP adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.TransactionHashClaims.
// Sets related.R.TransactionHash appropriately.
// Panics on error.
func (o *Transaction) AddTransactionHashClaimsP(exec boil.Executor, insert bool, related ...*Claim) {
	if err := o.AddTransactionHashClaims(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTransactionHashClaimsGP adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.TransactionHashClaims.
// Sets related.R.TransactionHash appropriately.
// Uses the global database handle and panics on error.
func (o *Transaction) AddTransactionHashClaimsGP(insert bool, related ...*Claim) {
	if err := o.AddTransactionHashClaims(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTransactionHashClaims adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.TransactionHashClaims.
// Sets related.R.TransactionHash appropriately.
func (o *Transaction) AddTransactionHashClaims(exec boil.Executor, insert bool, related ...*Claim) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.TransactionHashID.String = o.Hash
			rel.TransactionHashID.Valid = true
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `claim` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"transaction_hash_id"}),
				strmangle.WhereClause("`", "`", 0, claimPrimaryKeyColumns),
			)
			values := []interface{}{o.Hash, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.TransactionHashID.String = o.Hash
			rel.TransactionHashID.Valid = true
		}
	}

	if o.R == nil {
		o.R = &transactionR{
			TransactionHashClaims: related,
		}
	} else {
		o.R.TransactionHashClaims = append(o.R.TransactionHashClaims, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &claimR{
				TransactionHash: o,
			}
		} else {
			rel.R.TransactionHash = o
		}
	}
	return nil
}

// SetTransactionHashClaimsG removes all previously related items of the
// transaction replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TransactionHash's TransactionHashClaims accordingly.
// Replaces o.R.TransactionHashClaims with related.
// Sets related.R.TransactionHash's TransactionHashClaims accordingly.
// Uses the global database handle.
func (o *Transaction) SetTransactionHashClaimsG(insert bool, related ...*Claim) error {
	return o.SetTransactionHashClaims(boil.GetDB(), insert, related...)
}

// SetTransactionHashClaimsP removes all previously related items of the
// transaction replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TransactionHash's TransactionHashClaims accordingly.
// Replaces o.R.TransactionHashClaims with related.
// Sets related.R.TransactionHash's TransactionHashClaims accordingly.
// Panics on error.
func (o *Transaction) SetTransactionHashClaimsP(exec boil.Executor, insert bool, related ...*Claim) {
	if err := o.SetTransactionHashClaims(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTransactionHashClaimsGP removes all previously related items of the
// transaction replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TransactionHash's TransactionHashClaims accordingly.
// Replaces o.R.TransactionHashClaims with related.
// Sets related.R.TransactionHash's TransactionHashClaims accordingly.
// Uses the global database handle and panics on error.
func (o *Transaction) SetTransactionHashClaimsGP(insert bool, related ...*Claim) {
	if err := o.SetTransactionHashClaims(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTransactionHashClaims removes all previously related items of the
// transaction replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TransactionHash's TransactionHashClaims accordingly.
// Replaces o.R.TransactionHashClaims with related.
// Sets related.R.TransactionHash's TransactionHashClaims accordingly.
func (o *Transaction) SetTransactionHashClaims(exec boil.Executor, insert bool, related ...*Claim) error {
	query := "update `claim` set `transaction_hash_id` = null where `transaction_hash_id` = ?"
	values := []interface{}{o.Hash}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.TransactionHashClaims {
			rel.TransactionHashID.Valid = false
			if rel.R == nil {
				continue
			}

			rel.R.TransactionHash = nil
		}

		o.R.TransactionHashClaims = nil
	}
	return o.AddTransactionHashClaims(exec, insert, related...)
}

// RemoveTransactionHashClaimsG relationships from objects passed in.
// Removes related items from R.TransactionHashClaims (uses pointer comparison, removal does not keep order)
// Sets related.R.TransactionHash.
// Uses the global database handle.
func (o *Transaction) RemoveTransactionHashClaimsG(related ...*Claim) error {
	return o.RemoveTransactionHashClaims(boil.GetDB(), related...)
}

// RemoveTransactionHashClaimsP relationships from objects passed in.
// Removes related items from R.TransactionHashClaims (uses pointer comparison, removal does not keep order)
// Sets related.R.TransactionHash.
// Panics on error.
func (o *Transaction) RemoveTransactionHashClaimsP(exec boil.Executor, related ...*Claim) {
	if err := o.RemoveTransactionHashClaims(exec, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveTransactionHashClaimsGP relationships from objects passed in.
// Removes related items from R.TransactionHashClaims (uses pointer comparison, removal does not keep order)
// Sets related.R.TransactionHash.
// Uses the global database handle and panics on error.
func (o *Transaction) RemoveTransactionHashClaimsGP(related ...*Claim) {
	if err := o.RemoveTransactionHashClaims(boil.GetDB(), related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveTransactionHashClaims relationships from objects passed in.
// Removes related items from R.TransactionHashClaims (uses pointer comparison, removal does not keep order)
// Sets related.R.TransactionHash.
func (o *Transaction) RemoveTransactionHashClaims(exec boil.Executor, related ...*Claim) error {
	var err error
	for _, rel := range related {
		rel.TransactionHashID.Valid = false
		if rel.R != nil {
			rel.R.TransactionHash = nil
		}
		if err = rel.Update(exec, "transaction_hash_id"); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.TransactionHashClaims {
			if rel != ri {
				continue
			}

			ln := len(o.R.TransactionHashClaims)
			if ln > 1 && i < ln-1 {
				o.R.TransactionHashClaims[i] = o.R.TransactionHashClaims[ln-1]
			}
			o.R.TransactionHashClaims = o.R.TransactionHashClaims[:ln-1]
			break
		}
	}

	return nil
}

// AddInputsG adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.Inputs.
// Sets related.R.Transaction appropriately.
// Uses the global database handle.
func (o *Transaction) AddInputsG(insert bool, related ...*Input) error {
	return o.AddInputs(boil.GetDB(), insert, related...)
}

// AddInputsP adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.Inputs.
// Sets related.R.Transaction appropriately.
// Panics on error.
func (o *Transaction) AddInputsP(exec boil.Executor, insert bool, related ...*Input) {
	if err := o.AddInputs(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddInputsGP adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.Inputs.
// Sets related.R.Transaction appropriately.
// Uses the global database handle and panics on error.
func (o *Transaction) AddInputsGP(insert bool, related ...*Input) {
	if err := o.AddInputs(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddInputs adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.Inputs.
// Sets related.R.Transaction appropriately.
func (o *Transaction) AddInputs(exec boil.Executor, insert bool, related ...*Input) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.TransactionID = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `input` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"transaction_id"}),
				strmangle.WhereClause("`", "`", 0, inputPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.TransactionID = o.ID
		}
	}

	if o.R == nil {
		o.R = &transactionR{
			Inputs: related,
		}
	} else {
		o.R.Inputs = append(o.R.Inputs, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &inputR{
				Transaction: o,
			}
		} else {
			rel.R.Transaction = o
		}
	}
	return nil
}

// AddOutputsG adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.Outputs.
// Sets related.R.Transaction appropriately.
// Uses the global database handle.
func (o *Transaction) AddOutputsG(insert bool, related ...*Output) error {
	return o.AddOutputs(boil.GetDB(), insert, related...)
}

// AddOutputsP adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.Outputs.
// Sets related.R.Transaction appropriately.
// Panics on error.
func (o *Transaction) AddOutputsP(exec boil.Executor, insert bool, related ...*Output) {
	if err := o.AddOutputs(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddOutputsGP adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.Outputs.
// Sets related.R.Transaction appropriately.
// Uses the global database handle and panics on error.
func (o *Transaction) AddOutputsGP(insert bool, related ...*Output) {
	if err := o.AddOutputs(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddOutputs adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.Outputs.
// Sets related.R.Transaction appropriately.
func (o *Transaction) AddOutputs(exec boil.Executor, insert bool, related ...*Output) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.TransactionID = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `output` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"transaction_id"}),
				strmangle.WhereClause("`", "`", 0, outputPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.TransactionID = o.ID
		}
	}

	if o.R == nil {
		o.R = &transactionR{
			Outputs: related,
		}
	} else {
		o.R.Outputs = append(o.R.Outputs, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &outputR{
				Transaction: o,
			}
		} else {
			rel.R.Transaction = o
		}
	}
	return nil
}

// AddTransactionHashSupportsG adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.TransactionHashSupports.
// Sets related.R.TransactionHash appropriately.
// Uses the global database handle.
func (o *Transaction) AddTransactionHashSupportsG(insert bool, related ...*Support) error {
	return o.AddTransactionHashSupports(boil.GetDB(), insert, related...)
}

// AddTransactionHashSupportsP adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.TransactionHashSupports.
// Sets related.R.TransactionHash appropriately.
// Panics on error.
func (o *Transaction) AddTransactionHashSupportsP(exec boil.Executor, insert bool, related ...*Support) {
	if err := o.AddTransactionHashSupports(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTransactionHashSupportsGP adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.TransactionHashSupports.
// Sets related.R.TransactionHash appropriately.
// Uses the global database handle and panics on error.
func (o *Transaction) AddTransactionHashSupportsGP(insert bool, related ...*Support) {
	if err := o.AddTransactionHashSupports(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTransactionHashSupports adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.TransactionHashSupports.
// Sets related.R.TransactionHash appropriately.
func (o *Transaction) AddTransactionHashSupports(exec boil.Executor, insert bool, related ...*Support) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.TransactionHashID.String = o.Hash
			rel.TransactionHashID.Valid = true
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `support` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"transaction_hash_id"}),
				strmangle.WhereClause("`", "`", 0, supportPrimaryKeyColumns),
			)
			values := []interface{}{o.Hash, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.TransactionHashID.String = o.Hash
			rel.TransactionHashID.Valid = true
		}
	}

	if o.R == nil {
		o.R = &transactionR{
			TransactionHashSupports: related,
		}
	} else {
		o.R.TransactionHashSupports = append(o.R.TransactionHashSupports, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &supportR{
				TransactionHash: o,
			}
		} else {
			rel.R.TransactionHash = o
		}
	}
	return nil
}

// SetTransactionHashSupportsG removes all previously related items of the
// transaction replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TransactionHash's TransactionHashSupports accordingly.
// Replaces o.R.TransactionHashSupports with related.
// Sets related.R.TransactionHash's TransactionHashSupports accordingly.
// Uses the global database handle.
func (o *Transaction) SetTransactionHashSupportsG(insert bool, related ...*Support) error {
	return o.SetTransactionHashSupports(boil.GetDB(), insert, related...)
}

// SetTransactionHashSupportsP removes all previously related items of the
// transaction replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TransactionHash's TransactionHashSupports accordingly.
// Replaces o.R.TransactionHashSupports with related.
// Sets related.R.TransactionHash's TransactionHashSupports accordingly.
// Panics on error.
func (o *Transaction) SetTransactionHashSupportsP(exec boil.Executor, insert bool, related ...*Support) {
	if err := o.SetTransactionHashSupports(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTransactionHashSupportsGP removes all previously related items of the
// transaction replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TransactionHash's TransactionHashSupports accordingly.
// Replaces o.R.TransactionHashSupports with related.
// Sets related.R.TransactionHash's TransactionHashSupports accordingly.
// Uses the global database handle and panics on error.
func (o *Transaction) SetTransactionHashSupportsGP(insert bool, related ...*Support) {
	if err := o.SetTransactionHashSupports(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTransactionHashSupports removes all previously related items of the
// transaction replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TransactionHash's TransactionHashSupports accordingly.
// Replaces o.R.TransactionHashSupports with related.
// Sets related.R.TransactionHash's TransactionHashSupports accordingly.
func (o *Transaction) SetTransactionHashSupports(exec boil.Executor, insert bool, related ...*Support) error {
	query := "update `support` set `transaction_hash_id` = null where `transaction_hash_id` = ?"
	values := []interface{}{o.Hash}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.TransactionHashSupports {
			rel.TransactionHashID.Valid = false
			if rel.R == nil {
				continue
			}

			rel.R.TransactionHash = nil
		}

		o.R.TransactionHashSupports = nil
	}
	return o.AddTransactionHashSupports(exec, insert, related...)
}

// RemoveTransactionHashSupportsG relationships from objects passed in.
// Removes related items from R.TransactionHashSupports (uses pointer comparison, removal does not keep order)
// Sets related.R.TransactionHash.
// Uses the global database handle.
func (o *Transaction) RemoveTransactionHashSupportsG(related ...*Support) error {
	return o.RemoveTransactionHashSupports(boil.GetDB(), related...)
}

// RemoveTransactionHashSupportsP relationships from objects passed in.
// Removes related items from R.TransactionHashSupports (uses pointer comparison, removal does not keep order)
// Sets related.R.TransactionHash.
// Panics on error.
func (o *Transaction) RemoveTransactionHashSupportsP(exec boil.Executor, related ...*Support) {
	if err := o.RemoveTransactionHashSupports(exec, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveTransactionHashSupportsGP relationships from objects passed in.
// Removes related items from R.TransactionHashSupports (uses pointer comparison, removal does not keep order)
// Sets related.R.TransactionHash.
// Uses the global database handle and panics on error.
func (o *Transaction) RemoveTransactionHashSupportsGP(related ...*Support) {
	if err := o.RemoveTransactionHashSupports(boil.GetDB(), related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveTransactionHashSupports relationships from objects passed in.
// Removes related items from R.TransactionHashSupports (uses pointer comparison, removal does not keep order)
// Sets related.R.TransactionHash.
func (o *Transaction) RemoveTransactionHashSupports(exec boil.Executor, related ...*Support) error {
	var err error
	for _, rel := range related {
		rel.TransactionHashID.Valid = false
		if rel.R != nil {
			rel.R.TransactionHash = nil
		}
		if err = rel.Update(exec, "transaction_hash_id"); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.TransactionHashSupports {
			if rel != ri {
				continue
			}

			ln := len(o.R.TransactionHashSupports)
			if ln > 1 && i < ln-1 {
				o.R.TransactionHashSupports[i] = o.R.TransactionHashSupports[ln-1]
			}
			o.R.TransactionHashSupports = o.R.TransactionHashSupports[:ln-1]
			break
		}
	}

	return nil
}

// AddTransactionAddressesG adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.TransactionAddresses.
// Sets related.R.Transaction appropriately.
// Uses the global database handle.
func (o *Transaction) AddTransactionAddressesG(insert bool, related ...*TransactionAddress) error {
	return o.AddTransactionAddresses(boil.GetDB(), insert, related...)
}

// AddTransactionAddressesP adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.TransactionAddresses.
// Sets related.R.Transaction appropriately.
// Panics on error.
func (o *Transaction) AddTransactionAddressesP(exec boil.Executor, insert bool, related ...*TransactionAddress) {
	if err := o.AddTransactionAddresses(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTransactionAddressesGP adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.TransactionAddresses.
// Sets related.R.Transaction appropriately.
// Uses the global database handle and panics on error.
func (o *Transaction) AddTransactionAddressesGP(insert bool, related ...*TransactionAddress) {
	if err := o.AddTransactionAddresses(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTransactionAddresses adds the given related objects to the existing relationships
// of the transaction, optionally inserting them as new records.
// Appends related to o.R.TransactionAddresses.
// Sets related.R.Transaction appropriately.
func (o *Transaction) AddTransactionAddresses(exec boil.Executor, insert bool, related ...*TransactionAddress) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.TransactionID = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `transaction_address` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"transaction_id"}),
				strmangle.WhereClause("`", "`", 0, transactionAddressPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.TransactionID, rel.AddressID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.TransactionID = o.ID
		}
	}

	if o.R == nil {
		o.R = &transactionR{
			TransactionAddresses: related,
		}
	} else {
		o.R.TransactionAddresses = append(o.R.TransactionAddresses, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &transactionAddressR{
				Transaction: o,
			}
		} else {
			rel.R.Transaction = o
		}
	}
	return nil
}

// TransactionsG retrieves all records.
func TransactionsG(mods ...qm.QueryMod) transactionQuery {
	return Transactions(boil.GetDB(), mods...)
}

// Transactions retrieves all the records using an executor.
func Transactions(exec boil.Executor, mods ...qm.QueryMod) transactionQuery {
	mods = append(mods, qm.From("`transaction`"))
	return transactionQuery{NewQuery(exec, mods...)}
}

// FindTransactionG retrieves a single record by ID.
func FindTransactionG(id uint64, selectCols ...string) (*Transaction, error) {
	return FindTransaction(boil.GetDB(), id, selectCols...)
}

// FindTransactionGP retrieves a single record by ID, and panics on error.
func FindTransactionGP(id uint64, selectCols ...string) *Transaction {
	retobj, err := FindTransaction(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindTransaction retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTransaction(exec boil.Executor, id uint64, selectCols ...string) (*Transaction, error) {
	transactionObj := &Transaction{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `transaction` where `id`=?", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(transactionObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: unable to select from transaction")
	}

	return transactionObj, nil
}

// FindTransactionP retrieves a single record by ID with an executor, and panics on error.
func FindTransactionP(exec boil.Executor, id uint64, selectCols ...string) *Transaction {
	retobj, err := FindTransaction(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Transaction) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Transaction) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Transaction) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Transaction) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("model: no transaction provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(transactionColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	transactionInsertCacheMut.RLock()
	cache, cached := transactionInsertCache[key]
	transactionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			transactionColumns,
			transactionColumnsWithDefault,
			transactionColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(transactionType, transactionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(transactionType, transactionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `transaction` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `transaction` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `transaction` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, transactionPrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "model: unable to insert into transaction")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == transactionMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for transaction")
	}

CacheNoHooks:
	if !cached {
		transactionInsertCacheMut.Lock()
		transactionInsertCache[key] = cache
		transactionInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single Transaction record. See Update for
// whitelist behavior description.
func (o *Transaction) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Transaction record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Transaction) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Transaction, and panics on error.
// See Update for whitelist behavior description.
func (o *Transaction) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Transaction.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Transaction) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	key := makeCacheKey(whitelist, nil)
	transactionUpdateCacheMut.RLock()
	cache, cached := transactionUpdateCache[key]
	transactionUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			transactionColumns,
			transactionPrimaryKeyColumns,
			whitelist,
		)

		if len(wl) == 0 {
			return errors.New("model: unable to update transaction, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `transaction` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, transactionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(transactionType, transactionMapping, append(wl, transactionPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "model: unable to update transaction row")
	}

	if !cached {
		transactionUpdateCacheMut.Lock()
		transactionUpdateCache[key] = cache
		transactionUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q transactionQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q transactionQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "model: unable to update all for transaction")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o TransactionSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o TransactionSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o TransactionSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TransactionSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), transactionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `transaction` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, transactionPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "model: unable to update all in transaction slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Transaction) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Transaction) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Transaction) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Transaction) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("model: no transaction provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(transactionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	transactionUpsertCacheMut.RLock()
	cache, cached := transactionUpsertCache[key]
	transactionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			transactionColumns,
			transactionColumnsWithDefault,
			transactionColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			transactionColumns,
			transactionPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("model: unable to upsert transaction, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "transaction", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `transaction` WHERE `id`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(transactionType, transactionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(transactionType, transactionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "model: unable to upsert for transaction")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == transactionMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for transaction")
	}

CacheNoHooks:
	if !cached {
		transactionUpsertCacheMut.Lock()
		transactionUpsertCache[key] = cache
		transactionUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteP deletes a single Transaction record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Transaction) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Transaction record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Transaction) DeleteG() error {
	if o == nil {
		return errors.New("model: no Transaction provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Transaction record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Transaction) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Transaction record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Transaction) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("model: no Transaction provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), transactionPrimaryKeyMapping)
	sql := "DELETE FROM `transaction` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "model: unable to delete from transaction")
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q transactionQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q transactionQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("model: no transactionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "model: unable to delete all from transaction")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o TransactionSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o TransactionSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("model: no Transaction slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o TransactionSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TransactionSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("model: no Transaction slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), transactionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `transaction` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, transactionPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "model: unable to delete all from transaction slice")
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Transaction) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Transaction) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Transaction) ReloadG() error {
	if o == nil {
		return errors.New("model: no Transaction provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Transaction) Reload(exec boil.Executor) error {
	ret, err := FindTransaction(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *TransactionSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *TransactionSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TransactionSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("model: empty TransactionSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TransactionSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	transactions := TransactionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), transactionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `transaction`.* FROM `transaction` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, transactionPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&transactions)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in TransactionSlice")
	}

	*o = transactions

	return nil
}

// TransactionExists checks if the Transaction row exists.
func TransactionExists(exec boil.Executor, id uint64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `transaction` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if transaction exists")
	}

	return exists, nil
}

// TransactionExistsG checks if the Transaction row exists.
func TransactionExistsG(id uint64) (bool, error) {
	return TransactionExists(boil.GetDB(), id)
}

// TransactionExistsGP checks if the Transaction row exists. Panics on error.
func TransactionExistsGP(id uint64) bool {
	e, err := TransactionExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// TransactionExistsP checks if the Transaction row exists. Panics on error.
func TransactionExistsP(exec boil.Executor, id uint64) bool {
	e, err := TransactionExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
