// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// Block is an object representing the database table.
type Block struct {
	Bits                  string      `boil:"bits" json:"bits" toml:"bits" yaml:"bits"`
	Chainwork             string      `boil:"chainwork" json:"chainwork" toml:"chainwork" yaml:"chainwork"`
	Confirmations         uint        `boil:"confirmations" json:"confirmations" toml:"confirmations" yaml:"confirmations"`
	Difficulty            string      `boil:"difficulty" json:"difficulty" toml:"difficulty" yaml:"difficulty"`
	Hash                  string      `boil:"hash" json:"hash" toml:"hash" yaml:"hash"`
	Height                uint64      `boil:"height" json:"height" toml:"height" yaml:"height"`
	MedianTime            uint64      `boil:"median_time" json:"median_time" toml:"median_time" yaml:"median_time"`
	MerkleRoot            string      `boil:"merkle_root" json:"merkle_root" toml:"merkle_root" yaml:"merkle_root"`
	NameClaimRoot         string      `boil:"name_claim_root" json:"name_claim_root" toml:"name_claim_root" yaml:"name_claim_root"`
	Nonce                 uint64      `boil:"nonce" json:"nonce" toml:"nonce" yaml:"nonce"`
	PreviousBlockID       null.String `boil:"previous_block_id" json:"previous_block_id,omitempty" toml:"previous_block_id" yaml:"previous_block_id,omitempty"`
	NextBlockID           null.String `boil:"next_block_id" json:"next_block_id,omitempty" toml:"next_block_id" yaml:"next_block_id,omitempty"`
	BlockSize             uint64      `boil:"block_size" json:"block_size" toml:"block_size" yaml:"block_size"`
	Target                string      `boil:"target" json:"target" toml:"target" yaml:"target"`
	BlockTime             uint64      `boil:"block_time" json:"block_time" toml:"block_time" yaml:"block_time"`
	Version               uint64      `boil:"version" json:"version" toml:"version" yaml:"version"`
	VersionHex            string      `boil:"version_hex" json:"version_hex" toml:"version_hex" yaml:"version_hex"`
	TransactionHashes     string      `boil:"transaction_hashes" json:"transaction_hashes" toml:"transaction_hashes" yaml:"transaction_hashes"`
	TransactionsProcessed bool        `boil:"transactions_processed" json:"transactions_processed" toml:"transactions_processed" yaml:"transactions_processed"`

	R *blockR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L blockL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BlockColumns = struct {
	Bits                  string
	Chainwork             string
	Confirmations         string
	Difficulty            string
	Hash                  string
	Height                string
	MedianTime            string
	MerkleRoot            string
	NameClaimRoot         string
	Nonce                 string
	PreviousBlockID       string
	NextBlockID           string
	BlockSize             string
	Target                string
	BlockTime             string
	Version               string
	VersionHex            string
	TransactionHashes     string
	TransactionsProcessed string
}{
	Bits:                  "bits",
	Chainwork:             "chainwork",
	Confirmations:         "confirmations",
	Difficulty:            "difficulty",
	Hash:                  "hash",
	Height:                "height",
	MedianTime:            "median_time",
	MerkleRoot:            "merkle_root",
	NameClaimRoot:         "name_claim_root",
	Nonce:                 "nonce",
	PreviousBlockID:       "previous_block_id",
	NextBlockID:           "next_block_id",
	BlockSize:             "block_size",
	Target:                "target",
	BlockTime:             "block_time",
	Version:               "version",
	VersionHex:            "version_hex",
	TransactionHashes:     "transaction_hashes",
	TransactionsProcessed: "transactions_processed",
}

// blockR is where relationships are stored.
type blockR struct {
	NextBlock           *Block
	PreviousBlock       *Block
	NextBlockBlocks     BlockSlice
	PreviousBlockBlocks BlockSlice
	Transactions        TransactionSlice
}

// blockL is where Load methods for each relationship are stored.
type blockL struct{}

var (
	blockColumns               = []string{"bits", "chainwork", "confirmations", "difficulty", "hash", "height", "median_time", "merkle_root", "name_claim_root", "nonce", "previous_block_id", "next_block_id", "block_size", "target", "block_time", "version", "version_hex", "transaction_hashes", "transactions_processed"}
	blockColumnsWithoutDefault = []string{"bits", "chainwork", "confirmations", "difficulty", "hash", "height", "median_time", "merkle_root", "name_claim_root", "nonce", "previous_block_id", "next_block_id", "block_size", "target", "block_time", "version", "version_hex", "transaction_hashes"}
	blockColumnsWithDefault    = []string{"transactions_processed"}
	blockPrimaryKeyColumns     = []string{"hash"}
)

type (
	// BlockSlice is an alias for a slice of pointers to Block.
	// This should generally be used opposed to []Block.
	BlockSlice []*Block

	blockQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	blockType                 = reflect.TypeOf(&Block{})
	blockMapping              = queries.MakeStructMapping(blockType)
	blockPrimaryKeyMapping, _ = queries.BindMapping(blockType, blockMapping, blockPrimaryKeyColumns)
	blockInsertCacheMut       sync.RWMutex
	blockInsertCache          = make(map[string]insertCache)
	blockUpdateCacheMut       sync.RWMutex
	blockUpdateCache          = make(map[string]updateCache)
	blockUpsertCacheMut       sync.RWMutex
	blockUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)

// OneP returns a single block record from the query, and panics on error.
func (q blockQuery) OneP() *Block {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single block record from the query.
func (q blockQuery) One() (*Block, error) {
	o := &Block{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: failed to execute a one query for blocks")
	}

	return o, nil
}

// AllP returns all Block records from the query, and panics on error.
func (q blockQuery) AllP() BlockSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Block records from the query.
func (q blockQuery) All() (BlockSlice, error) {
	var o []*Block

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to Block slice")
	}

	return o, nil
}

// CountP returns the count of all Block records in the query, and panics on error.
func (q blockQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Block records in the query.
func (q blockQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count blocks rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q blockQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q blockQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if blocks exists")
	}

	return count > 0, nil
}

// NextBlockG pointed to by the foreign key.
func (o *Block) NextBlockG(mods ...qm.QueryMod) blockQuery {
	return o.NextBlock(boil.GetDB(), mods...)
}

// NextBlock pointed to by the foreign key.
func (o *Block) NextBlock(exec boil.Executor, mods ...qm.QueryMod) blockQuery {
	queryMods := []qm.QueryMod{
		qm.Where("hash=?", o.NextBlockID),
	}

	queryMods = append(queryMods, mods...)

	query := Blocks(exec, queryMods...)
	queries.SetFrom(query.Query, "`blocks`")

	return query
}

// PreviousBlockG pointed to by the foreign key.
func (o *Block) PreviousBlockG(mods ...qm.QueryMod) blockQuery {
	return o.PreviousBlock(boil.GetDB(), mods...)
}

// PreviousBlock pointed to by the foreign key.
func (o *Block) PreviousBlock(exec boil.Executor, mods ...qm.QueryMod) blockQuery {
	queryMods := []qm.QueryMod{
		qm.Where("hash=?", o.PreviousBlockID),
	}

	queryMods = append(queryMods, mods...)

	query := Blocks(exec, queryMods...)
	queries.SetFrom(query.Query, "`blocks`")

	return query
}

// NextBlockBlocksG retrieves all the block's blocks via next_block_id column.
func (o *Block) NextBlockBlocksG(mods ...qm.QueryMod) blockQuery {
	return o.NextBlockBlocks(boil.GetDB(), mods...)
}

// NextBlockBlocks retrieves all the block's blocks with an executor via next_block_id column.
func (o *Block) NextBlockBlocks(exec boil.Executor, mods ...qm.QueryMod) blockQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`blocks`.`next_block_id`=?", o.Hash),
	)

	query := Blocks(exec, queryMods...)
	queries.SetFrom(query.Query, "`blocks`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`blocks`.*"})
	}

	return query
}

// PreviousBlockBlocksG retrieves all the block's blocks via previous_block_id column.
func (o *Block) PreviousBlockBlocksG(mods ...qm.QueryMod) blockQuery {
	return o.PreviousBlockBlocks(boil.GetDB(), mods...)
}

// PreviousBlockBlocks retrieves all the block's blocks with an executor via previous_block_id column.
func (o *Block) PreviousBlockBlocks(exec boil.Executor, mods ...qm.QueryMod) blockQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`blocks`.`previous_block_id`=?", o.Hash),
	)

	query := Blocks(exec, queryMods...)
	queries.SetFrom(query.Query, "`blocks`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`blocks`.*"})
	}

	return query
}

// TransactionsG retrieves all the transaction's transactions.
func (o *Block) TransactionsG(mods ...qm.QueryMod) transactionQuery {
	return o.Transactions(boil.GetDB(), mods...)
}

// Transactions retrieves all the transaction's transactions with an executor.
func (o *Block) Transactions(exec boil.Executor, mods ...qm.QueryMod) transactionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`transactions`.`block_id`=?", o.Hash),
	)

	query := Transactions(exec, queryMods...)
	queries.SetFrom(query.Query, "`transactions`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`transactions`.*"})
	}

	return query
}

// LoadNextBlock allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (blockL) LoadNextBlock(e boil.Executor, singular bool, maybeBlock interface{}) error {
	var slice []*Block
	var object *Block

	count := 1
	if singular {
		object = maybeBlock.(*Block)
	} else {
		slice = *maybeBlock.(*[]*Block)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &blockR{}
		}
		args[0] = object.NextBlockID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &blockR{}
			}
			args[i] = obj.NextBlockID
		}
	}

	query := fmt.Sprintf(
		"select * from `blocks` where `hash` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Block")
	}
	defer results.Close()

	var resultSlice []*Block
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Block")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.NextBlock = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.NextBlockID.String == foreign.Hash {
				local.R.NextBlock = foreign
				break
			}
		}
	}

	return nil
}

// LoadPreviousBlock allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (blockL) LoadPreviousBlock(e boil.Executor, singular bool, maybeBlock interface{}) error {
	var slice []*Block
	var object *Block

	count := 1
	if singular {
		object = maybeBlock.(*Block)
	} else {
		slice = *maybeBlock.(*[]*Block)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &blockR{}
		}
		args[0] = object.PreviousBlockID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &blockR{}
			}
			args[i] = obj.PreviousBlockID
		}
	}

	query := fmt.Sprintf(
		"select * from `blocks` where `hash` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Block")
	}
	defer results.Close()

	var resultSlice []*Block
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Block")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.PreviousBlock = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PreviousBlockID.String == foreign.Hash {
				local.R.PreviousBlock = foreign
				break
			}
		}
	}

	return nil
}

// LoadNextBlockBlocks allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (blockL) LoadNextBlockBlocks(e boil.Executor, singular bool, maybeBlock interface{}) error {
	var slice []*Block
	var object *Block

	count := 1
	if singular {
		object = maybeBlock.(*Block)
	} else {
		slice = *maybeBlock.(*[]*Block)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &blockR{}
		}
		args[0] = object.Hash
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &blockR{}
			}
			args[i] = obj.Hash
		}
	}

	query := fmt.Sprintf(
		"select * from `blocks` where `next_block_id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load blocks")
	}
	defer results.Close()

	var resultSlice []*Block
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice blocks")
	}

	if singular {
		object.R.NextBlockBlocks = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Hash == foreign.NextBlockID.String {
				local.R.NextBlockBlocks = append(local.R.NextBlockBlocks, foreign)
				break
			}
		}
	}

	return nil
}

// LoadPreviousBlockBlocks allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (blockL) LoadPreviousBlockBlocks(e boil.Executor, singular bool, maybeBlock interface{}) error {
	var slice []*Block
	var object *Block

	count := 1
	if singular {
		object = maybeBlock.(*Block)
	} else {
		slice = *maybeBlock.(*[]*Block)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &blockR{}
		}
		args[0] = object.Hash
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &blockR{}
			}
			args[i] = obj.Hash
		}
	}

	query := fmt.Sprintf(
		"select * from `blocks` where `previous_block_id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load blocks")
	}
	defer results.Close()

	var resultSlice []*Block
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice blocks")
	}

	if singular {
		object.R.PreviousBlockBlocks = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Hash == foreign.PreviousBlockID.String {
				local.R.PreviousBlockBlocks = append(local.R.PreviousBlockBlocks, foreign)
				break
			}
		}
	}

	return nil
}

// LoadTransactions allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (blockL) LoadTransactions(e boil.Executor, singular bool, maybeBlock interface{}) error {
	var slice []*Block
	var object *Block

	count := 1
	if singular {
		object = maybeBlock.(*Block)
	} else {
		slice = *maybeBlock.(*[]*Block)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &blockR{}
		}
		args[0] = object.Hash
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &blockR{}
			}
			args[i] = obj.Hash
		}
	}

	query := fmt.Sprintf(
		"select * from `transactions` where `block_id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load transactions")
	}
	defer results.Close()

	var resultSlice []*Transaction
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice transactions")
	}

	if singular {
		object.R.Transactions = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Hash == foreign.BlockID {
				local.R.Transactions = append(local.R.Transactions, foreign)
				break
			}
		}
	}

	return nil
}

// SetNextBlockG of the block to the related item.
// Sets o.R.NextBlock to related.
// Adds o to related.R.NextBlockBlocks.
// Uses the global database handle.
func (o *Block) SetNextBlockG(insert bool, related *Block) error {
	return o.SetNextBlock(boil.GetDB(), insert, related)
}

// SetNextBlockP of the block to the related item.
// Sets o.R.NextBlock to related.
// Adds o to related.R.NextBlockBlocks.
// Panics on error.
func (o *Block) SetNextBlockP(exec boil.Executor, insert bool, related *Block) {
	if err := o.SetNextBlock(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetNextBlockGP of the block to the related item.
// Sets o.R.NextBlock to related.
// Adds o to related.R.NextBlockBlocks.
// Uses the global database handle and panics on error.
func (o *Block) SetNextBlockGP(insert bool, related *Block) {
	if err := o.SetNextBlock(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetNextBlock of the block to the related item.
// Sets o.R.NextBlock to related.
// Adds o to related.R.NextBlockBlocks.
func (o *Block) SetNextBlock(exec boil.Executor, insert bool, related *Block) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `blocks` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"next_block_id"}),
		strmangle.WhereClause("`", "`", 0, blockPrimaryKeyColumns),
	)
	values := []interface{}{related.Hash, o.Hash}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.NextBlockID.String = related.Hash
	o.NextBlockID.Valid = true

	if o.R == nil {
		o.R = &blockR{
			NextBlock: related,
		}
	} else {
		o.R.NextBlock = related
	}

	if related.R == nil {
		related.R = &blockR{
			NextBlockBlocks: BlockSlice{o},
		}
	} else {
		related.R.NextBlockBlocks = append(related.R.NextBlockBlocks, o)
	}

	return nil
}

// RemoveNextBlockG relationship.
// Sets o.R.NextBlock to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle.
func (o *Block) RemoveNextBlockG(related *Block) error {
	return o.RemoveNextBlock(boil.GetDB(), related)
}

// RemoveNextBlockP relationship.
// Sets o.R.NextBlock to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Panics on error.
func (o *Block) RemoveNextBlockP(exec boil.Executor, related *Block) {
	if err := o.RemoveNextBlock(exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveNextBlockGP relationship.
// Sets o.R.NextBlock to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle and panics on error.
func (o *Block) RemoveNextBlockGP(related *Block) {
	if err := o.RemoveNextBlock(boil.GetDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveNextBlock relationship.
// Sets o.R.NextBlock to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *Block) RemoveNextBlock(exec boil.Executor, related *Block) error {
	var err error

	o.NextBlockID.Valid = false
	if err = o.Update(exec, "next_block_id"); err != nil {
		o.NextBlockID.Valid = true
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.NextBlock = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.NextBlockBlocks {
		if o.NextBlockID.String != ri.NextBlockID.String {
			continue
		}

		ln := len(related.R.NextBlockBlocks)
		if ln > 1 && i < ln-1 {
			related.R.NextBlockBlocks[i] = related.R.NextBlockBlocks[ln-1]
		}
		related.R.NextBlockBlocks = related.R.NextBlockBlocks[:ln-1]
		break
	}
	return nil
}

// SetPreviousBlockG of the block to the related item.
// Sets o.R.PreviousBlock to related.
// Adds o to related.R.PreviousBlockBlocks.
// Uses the global database handle.
func (o *Block) SetPreviousBlockG(insert bool, related *Block) error {
	return o.SetPreviousBlock(boil.GetDB(), insert, related)
}

// SetPreviousBlockP of the block to the related item.
// Sets o.R.PreviousBlock to related.
// Adds o to related.R.PreviousBlockBlocks.
// Panics on error.
func (o *Block) SetPreviousBlockP(exec boil.Executor, insert bool, related *Block) {
	if err := o.SetPreviousBlock(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetPreviousBlockGP of the block to the related item.
// Sets o.R.PreviousBlock to related.
// Adds o to related.R.PreviousBlockBlocks.
// Uses the global database handle and panics on error.
func (o *Block) SetPreviousBlockGP(insert bool, related *Block) {
	if err := o.SetPreviousBlock(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetPreviousBlock of the block to the related item.
// Sets o.R.PreviousBlock to related.
// Adds o to related.R.PreviousBlockBlocks.
func (o *Block) SetPreviousBlock(exec boil.Executor, insert bool, related *Block) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `blocks` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"previous_block_id"}),
		strmangle.WhereClause("`", "`", 0, blockPrimaryKeyColumns),
	)
	values := []interface{}{related.Hash, o.Hash}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PreviousBlockID.String = related.Hash
	o.PreviousBlockID.Valid = true

	if o.R == nil {
		o.R = &blockR{
			PreviousBlock: related,
		}
	} else {
		o.R.PreviousBlock = related
	}

	if related.R == nil {
		related.R = &blockR{
			PreviousBlockBlocks: BlockSlice{o},
		}
	} else {
		related.R.PreviousBlockBlocks = append(related.R.PreviousBlockBlocks, o)
	}

	return nil
}

// RemovePreviousBlockG relationship.
// Sets o.R.PreviousBlock to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle.
func (o *Block) RemovePreviousBlockG(related *Block) error {
	return o.RemovePreviousBlock(boil.GetDB(), related)
}

// RemovePreviousBlockP relationship.
// Sets o.R.PreviousBlock to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Panics on error.
func (o *Block) RemovePreviousBlockP(exec boil.Executor, related *Block) {
	if err := o.RemovePreviousBlock(exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemovePreviousBlockGP relationship.
// Sets o.R.PreviousBlock to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle and panics on error.
func (o *Block) RemovePreviousBlockGP(related *Block) {
	if err := o.RemovePreviousBlock(boil.GetDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemovePreviousBlock relationship.
// Sets o.R.PreviousBlock to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *Block) RemovePreviousBlock(exec boil.Executor, related *Block) error {
	var err error

	o.PreviousBlockID.Valid = false
	if err = o.Update(exec, "previous_block_id"); err != nil {
		o.PreviousBlockID.Valid = true
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.PreviousBlock = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.PreviousBlockBlocks {
		if o.PreviousBlockID.String != ri.PreviousBlockID.String {
			continue
		}

		ln := len(related.R.PreviousBlockBlocks)
		if ln > 1 && i < ln-1 {
			related.R.PreviousBlockBlocks[i] = related.R.PreviousBlockBlocks[ln-1]
		}
		related.R.PreviousBlockBlocks = related.R.PreviousBlockBlocks[:ln-1]
		break
	}
	return nil
}

// AddNextBlockBlocksG adds the given related objects to the existing relationships
// of the block, optionally inserting them as new records.
// Appends related to o.R.NextBlockBlocks.
// Sets related.R.NextBlock appropriately.
// Uses the global database handle.
func (o *Block) AddNextBlockBlocksG(insert bool, related ...*Block) error {
	return o.AddNextBlockBlocks(boil.GetDB(), insert, related...)
}

// AddNextBlockBlocksP adds the given related objects to the existing relationships
// of the block, optionally inserting them as new records.
// Appends related to o.R.NextBlockBlocks.
// Sets related.R.NextBlock appropriately.
// Panics on error.
func (o *Block) AddNextBlockBlocksP(exec boil.Executor, insert bool, related ...*Block) {
	if err := o.AddNextBlockBlocks(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddNextBlockBlocksGP adds the given related objects to the existing relationships
// of the block, optionally inserting them as new records.
// Appends related to o.R.NextBlockBlocks.
// Sets related.R.NextBlock appropriately.
// Uses the global database handle and panics on error.
func (o *Block) AddNextBlockBlocksGP(insert bool, related ...*Block) {
	if err := o.AddNextBlockBlocks(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddNextBlockBlocks adds the given related objects to the existing relationships
// of the block, optionally inserting them as new records.
// Appends related to o.R.NextBlockBlocks.
// Sets related.R.NextBlock appropriately.
func (o *Block) AddNextBlockBlocks(exec boil.Executor, insert bool, related ...*Block) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.NextBlockID.String = o.Hash
			rel.NextBlockID.Valid = true
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `blocks` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"next_block_id"}),
				strmangle.WhereClause("`", "`", 0, blockPrimaryKeyColumns),
			)
			values := []interface{}{o.Hash, rel.Hash}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.NextBlockID.String = o.Hash
			rel.NextBlockID.Valid = true
		}
	}

	if o.R == nil {
		o.R = &blockR{
			NextBlockBlocks: related,
		}
	} else {
		o.R.NextBlockBlocks = append(o.R.NextBlockBlocks, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &blockR{
				NextBlock: o,
			}
		} else {
			rel.R.NextBlock = o
		}
	}
	return nil
}

// SetNextBlockBlocksG removes all previously related items of the
// block replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.NextBlock's NextBlockBlocks accordingly.
// Replaces o.R.NextBlockBlocks with related.
// Sets related.R.NextBlock's NextBlockBlocks accordingly.
// Uses the global database handle.
func (o *Block) SetNextBlockBlocksG(insert bool, related ...*Block) error {
	return o.SetNextBlockBlocks(boil.GetDB(), insert, related...)
}

// SetNextBlockBlocksP removes all previously related items of the
// block replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.NextBlock's NextBlockBlocks accordingly.
// Replaces o.R.NextBlockBlocks with related.
// Sets related.R.NextBlock's NextBlockBlocks accordingly.
// Panics on error.
func (o *Block) SetNextBlockBlocksP(exec boil.Executor, insert bool, related ...*Block) {
	if err := o.SetNextBlockBlocks(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetNextBlockBlocksGP removes all previously related items of the
// block replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.NextBlock's NextBlockBlocks accordingly.
// Replaces o.R.NextBlockBlocks with related.
// Sets related.R.NextBlock's NextBlockBlocks accordingly.
// Uses the global database handle and panics on error.
func (o *Block) SetNextBlockBlocksGP(insert bool, related ...*Block) {
	if err := o.SetNextBlockBlocks(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetNextBlockBlocks removes all previously related items of the
// block replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.NextBlock's NextBlockBlocks accordingly.
// Replaces o.R.NextBlockBlocks with related.
// Sets related.R.NextBlock's NextBlockBlocks accordingly.
func (o *Block) SetNextBlockBlocks(exec boil.Executor, insert bool, related ...*Block) error {
	query := "update `blocks` set `next_block_id` = null where `next_block_id` = ?"
	values := []interface{}{o.Hash}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.NextBlockBlocks {
			rel.NextBlockID.Valid = false
			if rel.R == nil {
				continue
			}

			rel.R.NextBlock = nil
		}

		o.R.NextBlockBlocks = nil
	}
	return o.AddNextBlockBlocks(exec, insert, related...)
}

// RemoveNextBlockBlocksG relationships from objects passed in.
// Removes related items from R.NextBlockBlocks (uses pointer comparison, removal does not keep order)
// Sets related.R.NextBlock.
// Uses the global database handle.
func (o *Block) RemoveNextBlockBlocksG(related ...*Block) error {
	return o.RemoveNextBlockBlocks(boil.GetDB(), related...)
}

// RemoveNextBlockBlocksP relationships from objects passed in.
// Removes related items from R.NextBlockBlocks (uses pointer comparison, removal does not keep order)
// Sets related.R.NextBlock.
// Panics on error.
func (o *Block) RemoveNextBlockBlocksP(exec boil.Executor, related ...*Block) {
	if err := o.RemoveNextBlockBlocks(exec, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveNextBlockBlocksGP relationships from objects passed in.
// Removes related items from R.NextBlockBlocks (uses pointer comparison, removal does not keep order)
// Sets related.R.NextBlock.
// Uses the global database handle and panics on error.
func (o *Block) RemoveNextBlockBlocksGP(related ...*Block) {
	if err := o.RemoveNextBlockBlocks(boil.GetDB(), related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveNextBlockBlocks relationships from objects passed in.
// Removes related items from R.NextBlockBlocks (uses pointer comparison, removal does not keep order)
// Sets related.R.NextBlock.
func (o *Block) RemoveNextBlockBlocks(exec boil.Executor, related ...*Block) error {
	var err error
	for _, rel := range related {
		rel.NextBlockID.Valid = false
		if rel.R != nil {
			rel.R.NextBlock = nil
		}
		if err = rel.Update(exec, "next_block_id"); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.NextBlockBlocks {
			if rel != ri {
				continue
			}

			ln := len(o.R.NextBlockBlocks)
			if ln > 1 && i < ln-1 {
				o.R.NextBlockBlocks[i] = o.R.NextBlockBlocks[ln-1]
			}
			o.R.NextBlockBlocks = o.R.NextBlockBlocks[:ln-1]
			break
		}
	}

	return nil
}

// AddPreviousBlockBlocksG adds the given related objects to the existing relationships
// of the block, optionally inserting them as new records.
// Appends related to o.R.PreviousBlockBlocks.
// Sets related.R.PreviousBlock appropriately.
// Uses the global database handle.
func (o *Block) AddPreviousBlockBlocksG(insert bool, related ...*Block) error {
	return o.AddPreviousBlockBlocks(boil.GetDB(), insert, related...)
}

// AddPreviousBlockBlocksP adds the given related objects to the existing relationships
// of the block, optionally inserting them as new records.
// Appends related to o.R.PreviousBlockBlocks.
// Sets related.R.PreviousBlock appropriately.
// Panics on error.
func (o *Block) AddPreviousBlockBlocksP(exec boil.Executor, insert bool, related ...*Block) {
	if err := o.AddPreviousBlockBlocks(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddPreviousBlockBlocksGP adds the given related objects to the existing relationships
// of the block, optionally inserting them as new records.
// Appends related to o.R.PreviousBlockBlocks.
// Sets related.R.PreviousBlock appropriately.
// Uses the global database handle and panics on error.
func (o *Block) AddPreviousBlockBlocksGP(insert bool, related ...*Block) {
	if err := o.AddPreviousBlockBlocks(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddPreviousBlockBlocks adds the given related objects to the existing relationships
// of the block, optionally inserting them as new records.
// Appends related to o.R.PreviousBlockBlocks.
// Sets related.R.PreviousBlock appropriately.
func (o *Block) AddPreviousBlockBlocks(exec boil.Executor, insert bool, related ...*Block) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.PreviousBlockID.String = o.Hash
			rel.PreviousBlockID.Valid = true
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `blocks` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"previous_block_id"}),
				strmangle.WhereClause("`", "`", 0, blockPrimaryKeyColumns),
			)
			values := []interface{}{o.Hash, rel.Hash}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.PreviousBlockID.String = o.Hash
			rel.PreviousBlockID.Valid = true
		}
	}

	if o.R == nil {
		o.R = &blockR{
			PreviousBlockBlocks: related,
		}
	} else {
		o.R.PreviousBlockBlocks = append(o.R.PreviousBlockBlocks, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &blockR{
				PreviousBlock: o,
			}
		} else {
			rel.R.PreviousBlock = o
		}
	}
	return nil
}

// SetPreviousBlockBlocksG removes all previously related items of the
// block replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.PreviousBlock's PreviousBlockBlocks accordingly.
// Replaces o.R.PreviousBlockBlocks with related.
// Sets related.R.PreviousBlock's PreviousBlockBlocks accordingly.
// Uses the global database handle.
func (o *Block) SetPreviousBlockBlocksG(insert bool, related ...*Block) error {
	return o.SetPreviousBlockBlocks(boil.GetDB(), insert, related...)
}

// SetPreviousBlockBlocksP removes all previously related items of the
// block replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.PreviousBlock's PreviousBlockBlocks accordingly.
// Replaces o.R.PreviousBlockBlocks with related.
// Sets related.R.PreviousBlock's PreviousBlockBlocks accordingly.
// Panics on error.
func (o *Block) SetPreviousBlockBlocksP(exec boil.Executor, insert bool, related ...*Block) {
	if err := o.SetPreviousBlockBlocks(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetPreviousBlockBlocksGP removes all previously related items of the
// block replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.PreviousBlock's PreviousBlockBlocks accordingly.
// Replaces o.R.PreviousBlockBlocks with related.
// Sets related.R.PreviousBlock's PreviousBlockBlocks accordingly.
// Uses the global database handle and panics on error.
func (o *Block) SetPreviousBlockBlocksGP(insert bool, related ...*Block) {
	if err := o.SetPreviousBlockBlocks(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetPreviousBlockBlocks removes all previously related items of the
// block replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.PreviousBlock's PreviousBlockBlocks accordingly.
// Replaces o.R.PreviousBlockBlocks with related.
// Sets related.R.PreviousBlock's PreviousBlockBlocks accordingly.
func (o *Block) SetPreviousBlockBlocks(exec boil.Executor, insert bool, related ...*Block) error {
	query := "update `blocks` set `previous_block_id` = null where `previous_block_id` = ?"
	values := []interface{}{o.Hash}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.PreviousBlockBlocks {
			rel.PreviousBlockID.Valid = false
			if rel.R == nil {
				continue
			}

			rel.R.PreviousBlock = nil
		}

		o.R.PreviousBlockBlocks = nil
	}
	return o.AddPreviousBlockBlocks(exec, insert, related...)
}

// RemovePreviousBlockBlocksG relationships from objects passed in.
// Removes related items from R.PreviousBlockBlocks (uses pointer comparison, removal does not keep order)
// Sets related.R.PreviousBlock.
// Uses the global database handle.
func (o *Block) RemovePreviousBlockBlocksG(related ...*Block) error {
	return o.RemovePreviousBlockBlocks(boil.GetDB(), related...)
}

// RemovePreviousBlockBlocksP relationships from objects passed in.
// Removes related items from R.PreviousBlockBlocks (uses pointer comparison, removal does not keep order)
// Sets related.R.PreviousBlock.
// Panics on error.
func (o *Block) RemovePreviousBlockBlocksP(exec boil.Executor, related ...*Block) {
	if err := o.RemovePreviousBlockBlocks(exec, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemovePreviousBlockBlocksGP relationships from objects passed in.
// Removes related items from R.PreviousBlockBlocks (uses pointer comparison, removal does not keep order)
// Sets related.R.PreviousBlock.
// Uses the global database handle and panics on error.
func (o *Block) RemovePreviousBlockBlocksGP(related ...*Block) {
	if err := o.RemovePreviousBlockBlocks(boil.GetDB(), related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemovePreviousBlockBlocks relationships from objects passed in.
// Removes related items from R.PreviousBlockBlocks (uses pointer comparison, removal does not keep order)
// Sets related.R.PreviousBlock.
func (o *Block) RemovePreviousBlockBlocks(exec boil.Executor, related ...*Block) error {
	var err error
	for _, rel := range related {
		rel.PreviousBlockID.Valid = false
		if rel.R != nil {
			rel.R.PreviousBlock = nil
		}
		if err = rel.Update(exec, "previous_block_id"); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.PreviousBlockBlocks {
			if rel != ri {
				continue
			}

			ln := len(o.R.PreviousBlockBlocks)
			if ln > 1 && i < ln-1 {
				o.R.PreviousBlockBlocks[i] = o.R.PreviousBlockBlocks[ln-1]
			}
			o.R.PreviousBlockBlocks = o.R.PreviousBlockBlocks[:ln-1]
			break
		}
	}

	return nil
}

// AddTransactionsG adds the given related objects to the existing relationships
// of the block, optionally inserting them as new records.
// Appends related to o.R.Transactions.
// Sets related.R.Block appropriately.
// Uses the global database handle.
func (o *Block) AddTransactionsG(insert bool, related ...*Transaction) error {
	return o.AddTransactions(boil.GetDB(), insert, related...)
}

// AddTransactionsP adds the given related objects to the existing relationships
// of the block, optionally inserting them as new records.
// Appends related to o.R.Transactions.
// Sets related.R.Block appropriately.
// Panics on error.
func (o *Block) AddTransactionsP(exec boil.Executor, insert bool, related ...*Transaction) {
	if err := o.AddTransactions(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTransactionsGP adds the given related objects to the existing relationships
// of the block, optionally inserting them as new records.
// Appends related to o.R.Transactions.
// Sets related.R.Block appropriately.
// Uses the global database handle and panics on error.
func (o *Block) AddTransactionsGP(insert bool, related ...*Transaction) {
	if err := o.AddTransactions(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTransactions adds the given related objects to the existing relationships
// of the block, optionally inserting them as new records.
// Appends related to o.R.Transactions.
// Sets related.R.Block appropriately.
func (o *Block) AddTransactions(exec boil.Executor, insert bool, related ...*Transaction) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.BlockID = o.Hash
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `transactions` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"block_id"}),
				strmangle.WhereClause("`", "`", 0, transactionPrimaryKeyColumns),
			)
			values := []interface{}{o.Hash, rel.Hash}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.BlockID = o.Hash
		}
	}

	if o.R == nil {
		o.R = &blockR{
			Transactions: related,
		}
	} else {
		o.R.Transactions = append(o.R.Transactions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &transactionR{
				Block: o,
			}
		} else {
			rel.R.Block = o
		}
	}
	return nil
}

// BlocksG retrieves all records.
func BlocksG(mods ...qm.QueryMod) blockQuery {
	return Blocks(boil.GetDB(), mods...)
}

// Blocks retrieves all the records using an executor.
func Blocks(exec boil.Executor, mods ...qm.QueryMod) blockQuery {
	mods = append(mods, qm.From("`blocks`"))
	return blockQuery{NewQuery(exec, mods...)}
}

// FindBlockG retrieves a single record by ID.
func FindBlockG(hash string, selectCols ...string) (*Block, error) {
	return FindBlock(boil.GetDB(), hash, selectCols...)
}

// FindBlockGP retrieves a single record by ID, and panics on error.
func FindBlockGP(hash string, selectCols ...string) *Block {
	retobj, err := FindBlock(boil.GetDB(), hash, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindBlock retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBlock(exec boil.Executor, hash string, selectCols ...string) (*Block, error) {
	blockObj := &Block{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `blocks` where `hash`=?", sel,
	)

	q := queries.Raw(exec, query, hash)

	err := q.Bind(blockObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: unable to select from blocks")
	}

	return blockObj, nil
}

// FindBlockP retrieves a single record by ID with an executor, and panics on error.
func FindBlockP(exec boil.Executor, hash string, selectCols ...string) *Block {
	retobj, err := FindBlock(exec, hash, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Block) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Block) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Block) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Block) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("model: no blocks provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(blockColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	blockInsertCacheMut.RLock()
	cache, cached := blockInsertCache[key]
	blockInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			blockColumns,
			blockColumnsWithDefault,
			blockColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(blockType, blockMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(blockType, blockMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `blocks` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `blocks` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `blocks` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, blockPrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	_, err = exec.Exec(cache.query, vals...)
	if err != nil {
		return errors.Wrap(err, "model: unable to insert into blocks")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.Hash,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for blocks")
	}

CacheNoHooks:
	if !cached {
		blockInsertCacheMut.Lock()
		blockInsertCache[key] = cache
		blockInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single Block record. See Update for
// whitelist behavior description.
func (o *Block) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Block record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Block) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Block, and panics on error.
// See Update for whitelist behavior description.
func (o *Block) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Block.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Block) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	key := makeCacheKey(whitelist, nil)
	blockUpdateCacheMut.RLock()
	cache, cached := blockUpdateCache[key]
	blockUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			blockColumns,
			blockPrimaryKeyColumns,
			whitelist,
		)

		if len(wl) == 0 {
			return errors.New("model: unable to update blocks, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `blocks` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, blockPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(blockType, blockMapping, append(wl, blockPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "model: unable to update blocks row")
	}

	if !cached {
		blockUpdateCacheMut.Lock()
		blockUpdateCache[key] = cache
		blockUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q blockQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q blockQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "model: unable to update all for blocks")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o BlockSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o BlockSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o BlockSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BlockSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), blockPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `blocks` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, blockPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "model: unable to update all in block slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Block) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Block) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Block) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Block) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("model: no blocks provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(blockColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	blockUpsertCacheMut.RLock()
	cache, cached := blockUpsertCache[key]
	blockUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			blockColumns,
			blockColumnsWithDefault,
			blockColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			blockColumns,
			blockPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("model: unable to upsert blocks, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "blocks", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `blocks` WHERE `hash`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(blockType, blockMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(blockType, blockMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	_, err = exec.Exec(cache.query, vals...)
	if err != nil {
		return errors.Wrap(err, "model: unable to upsert for blocks")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.Hash,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for blocks")
	}

CacheNoHooks:
	if !cached {
		blockUpsertCacheMut.Lock()
		blockUpsertCache[key] = cache
		blockUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteP deletes a single Block record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Block) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Block record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Block) DeleteG() error {
	if o == nil {
		return errors.New("model: no Block provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Block record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Block) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Block record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Block) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("model: no Block provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), blockPrimaryKeyMapping)
	sql := "DELETE FROM `blocks` WHERE `hash`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "model: unable to delete from blocks")
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q blockQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q blockQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("model: no blockQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "model: unable to delete all from blocks")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o BlockSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o BlockSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("model: no Block slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o BlockSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BlockSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("model: no Block slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), blockPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `blocks` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, blockPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "model: unable to delete all from block slice")
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Block) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Block) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Block) ReloadG() error {
	if o == nil {
		return errors.New("model: no Block provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Block) Reload(exec boil.Executor) error {
	ret, err := FindBlock(exec, o.Hash)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *BlockSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *BlockSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BlockSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("model: empty BlockSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BlockSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	blocks := BlockSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), blockPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `blocks`.* FROM `blocks` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, blockPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&blocks)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in BlockSlice")
	}

	*o = blocks

	return nil
}

// BlockExists checks if the Block row exists.
func BlockExists(exec boil.Executor, hash string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `blocks` where `hash`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, hash)
	}

	row := exec.QueryRow(sql, hash)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if blocks exists")
	}

	return exists, nil
}

// BlockExistsG checks if the Block row exists.
func BlockExistsG(hash string) (bool, error) {
	return BlockExists(boil.GetDB(), hash)
}

// BlockExistsGP checks if the Block row exists. Panics on error.
func BlockExistsGP(hash string) bool {
	e, err := BlockExists(boil.GetDB(), hash)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// BlockExistsP checks if the Block row exists. Panics on error.
func BlockExistsP(exec boil.Executor, hash string) bool {
	e, err := BlockExists(exec, hash)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
