// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

func testClaims(t *testing.T) {
	t.Parallel()

	query := Claims(nil)

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}
func testClaimsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = claim.Delete(tx); err != nil {
		t.Error(err)
	}

	count, err := Claims(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testClaimsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = Claims(tx).DeleteAll(); err != nil {
		t.Error(err)
	}

	count, err := Claims(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testClaimsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := ClaimSlice{claim}

	if err = slice.DeleteAll(tx); err != nil {
		t.Error(err)
	}

	count, err := Claims(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}
func testClaimsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx); err != nil {
		t.Error(err)
	}

	e, err := ClaimExists(tx, claim.ID)
	if err != nil {
		t.Errorf("Unable to check if Claim exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ClaimExistsG to return true, but got false.")
	}
}
func testClaimsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx); err != nil {
		t.Error(err)
	}

	claimFound, err := FindClaim(tx, claim.ID)
	if err != nil {
		t.Error(err)
	}

	if claimFound == nil {
		t.Error("want a record, got nil")
	}
}
func testClaimsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = Claims(tx).Bind(claim); err != nil {
		t.Error(err)
	}
}

func testClaimsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx); err != nil {
		t.Error(err)
	}

	if x, err := Claims(tx).One(); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testClaimsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	claimOne := &Claim{}
	claimTwo := &Claim{}
	if err = randomize.Struct(seed, claimOne, claimDBTypes, false, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}
	if err = randomize.Struct(seed, claimTwo, claimDBTypes, false, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claimOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = claimTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := Claims(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testClaimsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	claimOne := &Claim{}
	claimTwo := &Claim{}
	if err = randomize.Struct(seed, claimOne, claimDBTypes, false, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}
	if err = randomize.Struct(seed, claimTwo, claimDBTypes, false, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claimOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = claimTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Claims(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testClaimsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Claims(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testClaimsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx, claimColumnsWithoutDefault...); err != nil {
		t.Error(err)
	}

	count, err := Claims(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testClaimOneToOneClaimStreamUsingClaimStream(t *testing.T) {
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var foreign ClaimStream
	var local Claim

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &foreign, claimStreamDBTypes, true, claimStreamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClaimStream struct: %s", err)
	}
	if err := randomize.Struct(seed, &local, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	if err := local.Insert(tx); err != nil {
		t.Fatal(err)
	}

	foreign.ClaimID = local.ID
	if err := foreign.Insert(tx); err != nil {
		t.Fatal(err)
	}

	check, err := local.ClaimStream(tx).One()
	if err != nil {
		t.Fatal(err)
	}

	if check.ClaimID != foreign.ClaimID {
		t.Errorf("want: %v, got %v", foreign.ClaimID, check.ClaimID)
	}

	slice := ClaimSlice{&local}
	if err = local.L.LoadClaimStream(tx, false, (*[]*Claim)(&slice)); err != nil {
		t.Fatal(err)
	}
	if local.R.ClaimStream == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.ClaimStream = nil
	if err = local.L.LoadClaimStream(tx, true, &local); err != nil {
		t.Fatal(err)
	}
	if local.R.ClaimStream == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testClaimOneToOneSetOpClaimStreamUsingClaimStream(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Claim
	var b, c ClaimStream

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, claimStreamDBTypes, false, strmangle.SetComplement(claimStreamPrimaryKeyColumns, claimStreamColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, claimStreamDBTypes, false, strmangle.SetComplement(claimStreamPrimaryKeyColumns, claimStreamColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*ClaimStream{&b, &c} {
		err = a.SetClaimStream(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.ClaimStream != x {
			t.Error("relationship struct not set to correct value")
		}
		if x.R.Claim != &a {
			t.Error("failed to append to foreign relationship struct")
		}

		if a.ID != x.ClaimID {
			t.Error("foreign key was wrong value", a.ID)
		}

		if exists, err := ClaimStreamExists(tx, x.ClaimID); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'x' to exist")
		}

		if a.ID != x.ClaimID {
			t.Error("foreign key was wrong value", a.ID, x.ClaimID)
		}

		if err = x.Delete(tx); err != nil {
			t.Fatal("failed to delete x", err)
		}
	}
}
func testClaimToManyPublisherClaimClaims(t *testing.T) {
	var err error
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Claim
	var b, c Claim

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}

	randomize.Struct(seed, &b, claimDBTypes, false, claimColumnsWithDefault...)
	randomize.Struct(seed, &c, claimDBTypes, false, claimColumnsWithDefault...)

	b.PublisherClaimID.Valid = true
	c.PublisherClaimID.Valid = true
	b.PublisherClaimID.String = a.ClaimID
	c.PublisherClaimID.String = a.ClaimID
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx); err != nil {
		t.Fatal(err)
	}

	claim, err := a.PublisherClaimClaims(tx).All()
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range claim {
		if v.PublisherClaimID.String == b.PublisherClaimID.String {
			bFound = true
		}
		if v.PublisherClaimID.String == c.PublisherClaimID.String {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := ClaimSlice{&a}
	if err = a.L.LoadPublisherClaimClaims(tx, false, (*[]*Claim)(&slice)); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.PublisherClaimClaims); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.PublisherClaimClaims = nil
	if err = a.L.LoadPublisherClaimClaims(tx, true, &a); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.PublisherClaimClaims); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", claim)
	}
}

func testClaimToManyAddOpPublisherClaimClaims(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Claim
	var b, c, d, e Claim

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Claim{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Claim{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddPublisherClaimClaims(tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ClaimID != first.PublisherClaimID.String {
			t.Error("foreign key was wrong value", a.ClaimID, first.PublisherClaimID.String)
		}
		if a.ClaimID != second.PublisherClaimID.String {
			t.Error("foreign key was wrong value", a.ClaimID, second.PublisherClaimID.String)
		}

		if first.R.PublisherClaim != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.PublisherClaim != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.PublisherClaimClaims[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.PublisherClaimClaims[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.PublisherClaimClaims(tx).Count()
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testClaimToManySetOpPublisherClaimClaims(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Claim
	var b, c, d, e Claim

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Claim{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx); err != nil {
		t.Fatal(err)
	}

	err = a.SetPublisherClaimClaims(tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.PublisherClaimClaims(tx).Count()
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetPublisherClaimClaims(tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.PublisherClaimClaims(tx).Count()
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if b.PublisherClaimID.Valid {
		t.Error("want b's foreign key value to be nil")
	}
	if c.PublisherClaimID.Valid {
		t.Error("want c's foreign key value to be nil")
	}
	if a.ClaimID != d.PublisherClaimID.String {
		t.Error("foreign key was wrong value", a.ClaimID, d.PublisherClaimID.String)
	}
	if a.ClaimID != e.PublisherClaimID.String {
		t.Error("foreign key was wrong value", a.ClaimID, e.PublisherClaimID.String)
	}

	if b.R.PublisherClaim != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.PublisherClaim != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.PublisherClaim != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.PublisherClaim != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.PublisherClaimClaims[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.PublisherClaimClaims[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testClaimToManyRemoveOpPublisherClaimClaims(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Claim
	var b, c, d, e Claim

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Claim{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}

	err = a.AddPublisherClaimClaims(tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.PublisherClaimClaims(tx).Count()
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemovePublisherClaimClaims(tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.PublisherClaimClaims(tx).Count()
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if b.PublisherClaimID.Valid {
		t.Error("want b's foreign key value to be nil")
	}
	if c.PublisherClaimID.Valid {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.PublisherClaim != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.PublisherClaim != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.PublisherClaim != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.PublisherClaim != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.PublisherClaimClaims) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.PublisherClaimClaims[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.PublisherClaimClaims[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testClaimToOneClaimUsingPublisherClaim(t *testing.T) {
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var local Claim
	var foreign Claim

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, claimDBTypes, false, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	local.PublisherClaimID.Valid = true

	if err := foreign.Insert(tx); err != nil {
		t.Fatal(err)
	}

	local.PublisherClaimID.String = foreign.ClaimID
	if err := local.Insert(tx); err != nil {
		t.Fatal(err)
	}

	check, err := local.PublisherClaim(tx).One()
	if err != nil {
		t.Fatal(err)
	}

	if check.ClaimID != foreign.ClaimID {
		t.Errorf("want: %v, got %v", foreign.ClaimID, check.ClaimID)
	}

	slice := ClaimSlice{&local}
	if err = local.L.LoadPublisherClaim(tx, false, (*[]*Claim)(&slice)); err != nil {
		t.Fatal(err)
	}
	if local.R.PublisherClaim == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.PublisherClaim = nil
	if err = local.L.LoadPublisherClaim(tx, true, &local); err != nil {
		t.Fatal(err)
	}
	if local.R.PublisherClaim == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testClaimToOneTransactionUsingTransactionOfClaim(t *testing.T) {
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var local Claim
	var foreign Transaction

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, transactionDBTypes, false, transactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Transaction struct: %s", err)
	}

	local.TransactionOfClaimID.Valid = true

	if err := foreign.Insert(tx); err != nil {
		t.Fatal(err)
	}

	local.TransactionOfClaimID.String = foreign.Hash
	if err := local.Insert(tx); err != nil {
		t.Fatal(err)
	}

	check, err := local.TransactionOfClaim(tx).One()
	if err != nil {
		t.Fatal(err)
	}

	if check.Hash != foreign.Hash {
		t.Errorf("want: %v, got %v", foreign.Hash, check.Hash)
	}

	slice := ClaimSlice{&local}
	if err = local.L.LoadTransactionOfClaim(tx, false, (*[]*Claim)(&slice)); err != nil {
		t.Fatal(err)
	}
	if local.R.TransactionOfClaim == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.TransactionOfClaim = nil
	if err = local.L.LoadTransactionOfClaim(tx, true, &local); err != nil {
		t.Fatal(err)
	}
	if local.R.TransactionOfClaim == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testClaimToOneSetOpClaimUsingPublisherClaim(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Claim
	var b, c Claim

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Claim{&b, &c} {
		err = a.SetPublisherClaim(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.PublisherClaim != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.PublisherClaimClaims[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.PublisherClaimID.String != x.ClaimID {
			t.Error("foreign key was wrong value", a.PublisherClaimID.String)
		}

		zero := reflect.Zero(reflect.TypeOf(a.PublisherClaimID.String))
		reflect.Indirect(reflect.ValueOf(&a.PublisherClaimID.String)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.PublisherClaimID.String != x.ClaimID {
			t.Error("foreign key was wrong value", a.PublisherClaimID.String, x.ClaimID)
		}
	}
}

func testClaimToOneRemoveOpClaimUsingPublisherClaim(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Claim
	var b Claim

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(tx); err != nil {
		t.Fatal(err)
	}

	if err = a.SetPublisherClaim(tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemovePublisherClaim(tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.PublisherClaim(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.PublisherClaim != nil {
		t.Error("R struct entry should be nil")
	}

	if a.PublisherClaimID.Valid {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.PublisherClaimClaims) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testClaimToOneSetOpTransactionUsingTransactionOfClaim(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Claim
	var b, c Transaction

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, transactionDBTypes, false, strmangle.SetComplement(transactionPrimaryKeyColumns, transactionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, transactionDBTypes, false, strmangle.SetComplement(transactionPrimaryKeyColumns, transactionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Transaction{&b, &c} {
		err = a.SetTransactionOfClaim(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.TransactionOfClaim != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TransactionOfClaimClaims[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TransactionOfClaimID.String != x.Hash {
			t.Error("foreign key was wrong value", a.TransactionOfClaimID.String)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TransactionOfClaimID.String))
		reflect.Indirect(reflect.ValueOf(&a.TransactionOfClaimID.String)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TransactionOfClaimID.String != x.Hash {
			t.Error("foreign key was wrong value", a.TransactionOfClaimID.String, x.Hash)
		}
	}
}

func testClaimToOneRemoveOpTransactionUsingTransactionOfClaim(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Claim
	var b Transaction

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, transactionDBTypes, false, strmangle.SetComplement(transactionPrimaryKeyColumns, transactionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(tx); err != nil {
		t.Fatal(err)
	}

	if err = a.SetTransactionOfClaim(tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveTransactionOfClaim(tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.TransactionOfClaim(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.TransactionOfClaim != nil {
		t.Error("R struct entry should be nil")
	}

	if a.TransactionOfClaimID.Valid {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.TransactionOfClaimClaims) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testClaimsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = claim.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testClaimsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := ClaimSlice{claim}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}
func testClaimsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := Claims(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	claimDBTypes = map[string]string{`Author`: `varchar`, `Certificate`: `text`, `ClaimID`: `char`, `ClaimType`: `tinyint`, `ContentType`: `varchar`, `Created`: `datetime`, `Description`: `mediumtext`, `Fee`: `decimal`, `FeeCurrency`: `char`, `ID`: `bigint`, `IsFiltered`: `tinyint`, `IsNSFW`: `tinyint`, `Language`: `varchar`, `Modified`: `datetime`, `Name`: `varchar`, `PublisherClaimID`: `char`, `PublisherSig`: `varchar`, `ThumbnailURL`: `text`, `Title`: `text`, `TransactionOfClaimID`: `varchar`, `TransactionTime`: `int`, `VOut`: `int`, `Version`: `varchar`}
	_            = bytes.MinRead
)

func testClaimsUpdate(t *testing.T) {
	t.Parallel()

	if len(claimColumns) == len(claimPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Claims(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	if err = claim.Update(tx); err != nil {
		t.Error(err)
	}
}

func testClaimsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(claimColumns) == len(claimPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	claim := &Claim{}
	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Claims(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, claim, claimDBTypes, true, claimPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(claimColumns, claimPrimaryKeyColumns) {
		fields = claimColumns
	} else {
		fields = strmangle.SetComplement(
			claimColumns,
			claimPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(claim))
	updateMap := M{}
	for _, col := range fields {
		updateMap[col] = value.FieldByName(strmangle.TitleCase(col)).Interface()
	}

	slice := ClaimSlice{claim}
	if err = slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	}
}
func testClaimsUpsert(t *testing.T) {
	t.Parallel()

	if len(claimColumns) == len(claimPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	claim := Claim{}
	if err = randomize.Struct(seed, &claim, claimDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = claim.Upsert(tx, nil); err != nil {
		t.Errorf("Unable to upsert Claim: %s", err)
	}

	count, err := Claims(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &claim, claimDBTypes, false, claimPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Claim struct: %s", err)
	}

	if err = claim.Upsert(tx, nil); err != nil {
		t.Errorf("Unable to upsert Claim: %s", err)
	}

	count, err = Claims(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
