# coding: utf-8

"""
    Chain Query

    The LBRY blockchain is read into SQL where important structured information can be extracted through the Chain Query API.

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import sys
from setuptools import setup, find_packages

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Chain Query",
    author_email="",
    url="",
    keywords=["Swagger", "Chain Query"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    The LBRY blockchain is read into SQL where important structured information can be extracted through the Chain Query API.
    """
)
