lbrycrdurl="rpc://lbry:lbry@localhost:11337"
mysqldsn="chainquery:chainquery@tcp(localhost:3306)/chainquery_e2e_test"
blockchainname="lbrycrd_regtest"
#debugmode=true
#debugquerymode=true
#profilemode=true
#mysqlprofile=true
